### ISSUE TITLE
bam now makes FireFox not resolve and other domains

### ISSUE THREAD

**Issue by nwlucas** [jweslley/bam#8]
Following the instructions for installation on a Linux (specifically Debian 8) distribution results in two things happening:

1) Chrome (and possibly any browser based on Chromium) ignores bam!. This is likely due to a change in Chrome that make it no longer rely/use nsswitch.

2) Firefox now will not work for domain other than a TLD .dev

Is this the expected behavior?

**Comment by jweslley** [comment]
Both browsers need to be restarted in order to work properly. Are you using localtld?

**Comment by nwlucas** [comment]
Both browsers have been restarted numerous times, no change in effect. Also yes localtld was used as per documentation.

**Comment by jweslley** [comment]
@nwlucas , please run the following commands and paste the output here.

    getent hosts google.com
    getent hosts myapp.dev

Maybe is a browser-related issue.
