### ISSUE TITLE
Possible omission in configuration

### ISSUE THREAD

**Issue by nwlucas** [jweslley/bam#9]
After successful setup:

- Navigate to bam.dev
- My application with a Profile (from foreman) is recognized and can be started using the Procfile configuration

Issue arises when trying to navigate to the url for the app.
Details:

bam loaded from the directory directly above the one with my rails app.
bam.dev lists the app by name
Rails app is named MoonElastic
Attempt to navigate to moonelastic.dev returns a 404 message from bam in the browser as wells a cli message that moonelastic.dev is not found.

Did I miss a step somewhere?

**Comment by jweslley** [comment]
Hi @nwlucas ,

Maybe the problem is the camelcase-based name of your app. Try to rename your app to moon-elastic, just for test. If this is your problem, please tell me, I´ll fix it. Feeback is welcome!
